# bitwise
x=12
y=14
print('x=4 y=5')
print('bitwsie and',x & y)
print('bitwsie or',x | y)
print('bitwsie not',~x)
print('bitwsie not',~y)
print('bitwsie xor',x^y)
print()
print('bitwise result in binary')
print('x=4:',bin(x),'y=5:',bin(y))
print('bitwsie and',bin(x & y))
print('bitwsie or',bin(x | y))
print('bitwsie not',bin(~x))
print('bitwsie not',bin(~y))
print('bitwsie xor',bin(x^y))
print()
print('bitwise result in octal')
print('x=4:',oct(x),'y=5:',oct(y))
print('bitwsie and',oct(x & y))
print('bitwsie or',oct(x | y))
print('bitwsie not',oct(~x))
print('bitwsie not',oct(~y))
print('bitwsie xor',oct(x^y))
print()
print('bitwise result in hexa')
print('x=4:',hex(x),'y=5:',hex(y))
print('bitwsie and',hex(x & y))
print('bitwsie or',hex(x | y))
print('bitwsie not',hex(~x))
print('bitwsie not',hex(~y))
print('bitwsie xor',hex(x^y))

x=17
print('left shift',x<<2)
print('right shift',x>>2)
