#Iterations
file=open('script2.py','w')
file.write('import sys\n')
file.write('print(sys.path)\n')
file.write('x = 2\n')
file.write('print(x ** 32)')
file.close()
r=open('script2.py')
print(r.readline())
print(r.readline())
print(r.readline())
print(r.readline())
print(r.readline())
r1=open('script2.py')
print(r1.__next__())
print(r1.__next__())
print(r1.__next__())
print(r1.__next__())
for line in open('script2.py'):
    print(line,end='')
print('\n')
#Manual Iteration: iter and next
r2=open('script2.py')
print(next(r2))
print(next(r2))
